name: lite-rtstt
base: core24
version: '1.0.0'
summary: A real-time speech to text server.
description: A lightweight, efficient, real-time Speech-to-Text server.
  It combines WebRTC VAD, Silero VAD, and OpenAI Whisper.

grade: stable
confinement: strict
package-repositories:
  - type: apt
    components: [main]
    suites: [noble]
    key-id: F23C5A6CF475977595C89F51BA6932366A755776
    url: https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu
parts:
  lite-rtstt:
    plugin: python
    source: .
    python-packages:
      - setuptools
      - wheel
    build-packages:
      - python3.13
      - python3.13-venv
      - python3.13-dev
      - portaudio19-dev
      - build-essential
    stage-packages:
      - python3.13
      - python3.13-venv
      - libportaudio2
      - libgomp1
      - ffmpeg
    override-build: |
      python3.13 -m venv $SNAPCRAFT_PART_INSTALL --copies
      . $SNAPCRAFT_PART_INSTALL/bin/activate
      pip install -U pip setuptools wheel
      pip install .
apps:
  lite-rtstt:
    command: bin/python $SNAP/bin/lite-rtstt
    plugs:
      - network
      - network-bind
      - audio-record
      - audio-playback
      - home
  server:
    command: bin/python $SNAP/bin/lite-rtstt run
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind